
version: '3.8'

services:
  assistant:
    build: .
    container_name: unified_ai_assistant
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - ASSISTANT_MODE=production
      - WEB_PORT=5000
      - API_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - assistant_network

  # خدمة قاعدة البيانات للذاكرة طويلة المدى
  redis:
    image: redis:7-alpine
    container_name: assistant_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - assistant_network

networks:
  assistant_network:
    driver: bridge

volumes:
  redis_data:
